config/routes.rb
# == Route Map
#
#                                   Prefix Verb   URI Pattern                                                                                       Controller#Action
#                         new_user_session GET    /users/sign_in(.:format)                                                                          devise/sessions#new
#                             user_session POST   /users/sign_in(.:format)                                                                          devise/sessions#create
#                     destroy_user_session DELETE /users/sign_out(.:format)                                                                         devise/sessions#destroy
#                        new_user_password GET    /users/password/new(.:format)                                                                     devise/passwords#new
#                       edit_user_password GET    /users/password/edit(.:format)                                                                    devise/passwords#edit
#                            user_password PATCH  /users/password(.:format)                                                                         devise/passwords#update
#                                          PUT    /users/password(.:format)                                                                         devise/passwords#update
#                                          POST   /users/password(.:format)                                                                         devise/passwords#create
#                 cancel_user_registration GET    /users/cancel(.:format)                                                                           devise/registrations#cancel
#                    new_user_registration GET    /users/sign_up(.:format)                                                                          devise/registrations#new
#                   edit_user_registration GET    /users/edit(.:format)                                                                             devise/registrations#edit
#                        user_registration PATCH  /users(.:format)                                                                                  devise/registrations#update
#                                          PUT    /users(.:format)                                                                                  devise/registrations#update
#                                          DELETE /users(.:format)                                                                                  devise/registrations#destroy
#                                          POST   /users(.:format)                                                                                  devise/registrations#create
#                               statements GET    /statements(.:format)                                                                             statements#index
#                                          POST   /statements(.:format)                                                                             statements#create
#                            new_statement GET    /statements/new(.:format)                                                                         statements#new
#                           edit_statement GET    /statements/:id/edit(.:format)                                                                    statements#edit
#                                statement GET    /statements/:id(.:format)                                                                         statements#show
#                                          PATCH  /statements/:id(.:format)                                                                         statements#update
#                                          PUT    /statements/:id(.:format)                                                                         statements#update
#                                          DELETE /statements/:id(.:format)                                                                         statements#destroy
#                                     root GET    /                                                                                                 statements#index
#         turbo_recede_historical_location GET    /recede_historical_location(.:format)                                                             turbo/native/navigation#recede
#         turbo_resume_historical_location GET    /resume_historical_location(.:format)                                                             turbo/native/navigation#resume
#        turbo_refresh_historical_location GET    /refresh_historical_location(.:format)                                                            turbo/native/navigation#refresh
#                                     page GET    /pages/*id                                                                                        high_voltage/pages#show
#            rails_postmark_inbound_emails POST   /rails/action_mailbox/postmark/inbound_emails(.:format)                                           action_mailbox/ingresses/postmark/inbound_emails#create
#               rails_relay_inbound_emails POST   /rails/action_mailbox/relay/inbound_emails(.:format)                                              action_mailbox/ingresses/relay/inbound_emails#create
#            rails_sendgrid_inbound_emails POST   /rails/action_mailbox/sendgrid/inbound_emails(.:format)                                           action_mailbox/ingresses/sendgrid/inbound_emails#create
#      rails_mandrill_inbound_health_check GET    /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#health_check
#            rails_mandrill_inbound_emails POST   /rails/action_mailbox/mandrill/inbound_emails(.:format)                                           action_mailbox/ingresses/mandrill/inbound_emails#create
#             rails_mailgun_inbound_emails POST   /rails/action_mailbox/mailgun/inbound_emails/mime(.:format)                                       action_mailbox/ingresses/mailgun/inbound_emails#create
#           rails_conductor_inbound_emails GET    /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#index
#                                          POST   /rails/conductor/action_mailbox/inbound_emails(.:format)                                          rails/conductor/action_mailbox/inbound_emails#create
#        new_rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/new(.:format)                                      rails/conductor/action_mailbox/inbound_emails#new
#            rails_conductor_inbound_email GET    /rails/conductor/action_mailbox/inbound_emails/:id(.:format)                                      rails/conductor/action_mailbox/inbound_emails#show
# new_rails_conductor_inbound_email_source GET    /rails/conductor/action_mailbox/inbound_emails/sources/new(.:format)                              rails/conductor/action_mailbox/inbound_emails/sources#new
#    rails_conductor_inbound_email_sources POST   /rails/conductor/action_mailbox/inbound_emails/sources(.:format)                                  rails/conductor/action_mailbox/inbound_emails/sources#create
#    rails_conductor_inbound_email_reroute POST   /rails/conductor/action_mailbox/:inbound_email_id/reroute(.:format)                               rails/conductor/action_mailbox/reroutes#create
# rails_conductor_inbound_email_incinerate POST   /rails/conductor/action_mailbox/:inbound_email_id/incinerate(.:format)                            rails/conductor/action_mailbox/incinerates#create
#                       rails_service_blob GET    /rails/active_storage/blobs/redirect/:signed_id/*filename(.:format)                               active_storage/blobs/redirect#show
#                 rails_service_blob_proxy GET    /rails/active_storage/blobs/proxy/:signed_id/*filename(.:format)                                  active_storage/blobs/proxy#show
#                                          GET    /rails/active_storage/blobs/:signed_id/*filename(.:format)                                        active_storage/blobs/redirect#show
#                rails_blob_representation GET    /rails/active_storage/representations/redirect/:signed_blob_id/:variation_key/*filename(.:format) active_storage/representations/redirect#show
#          rails_blob_representation_proxy GET    /rails/active_storage/representations/proxy/:signed_blob_id/:variation_key/*filename(.:format)    active_storage/representations/proxy#show
#                                          GET    /rails/active_storage/representations/:signed_blob_id/:variation_key/*filename(.:format)          active_storage/representations/redirect#show
#                       rails_disk_service GET    /rails/active_storage/disk/:encoded_key/*filename(.:format)                                       active_storage/disk#show
#                update_rails_disk_service PUT    /rails/active_storage/disk/:encoded_token(.:format)                                               active_storage/disk#update
#                     rails_direct_uploads POST   /rails/active_storage/direct_uploads(.:format)                                                    active_storage/direct_uploads#create

Rails.application.routes.draw do
  devise_for :users
  resources :statements, only: [:index, :show, :new, :create] do
    resources :incomes, only: [:new, :create]
    resources :expenses, only: [:new, :create]
  end

  root "statements#index"
end

app/models/statement.rb
# == Schema Information
#
# Table name: statements
#
#  id         :bigint           not null, primary key
#  date       :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :bigint           not null
#
# Indexes
#
#  index_statements_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Statement < ApplicationRecord
  belongs_to :user
  has_many :incomes
  has_many :expenses

  validates :date, presence: true

  def total_income
    incomes.sum(:amount) || 0.0
  end

  def total_expense
    expenses.sum(:amount) || 0.0
  end

  def disposable_income
    total_income - total_expense
  end

  def expense_ratio
    total_expense / total_income
  end

  def rating
    case expense_ratio
    when 0...0.1 then 'A'
    when 0.1...0.3 then 'B'
    when 0.3...0.5 then 'C'
    when 0.5.. then 'D'
    else 'n/a'
    end
  end
end

app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  def index
    @statements = current_user.statements.order(date: :desc)
  end

  def show
    @statement = current_user.statements.find(params[:id])
  end

  def new
    @statement = Statement.new
  end

  def create
    @statement = Statement.new(statement_params.merge(user: current_user))

    respond_to do |format|
      if @statement.save
        format.html { redirect_to statement_url(@statement), notice: "Statement was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def statement_params
    params.require(:statement).permit(:date)
  end
end

app/views/statements/_form.html.slim
= simple_form_for(@statement) do |f|
  .space-y-8
    = f.input :date, html5: true, as: :date
    .text-right
      = f.button :submit

app/views/statements/index.html.slim
.container.mx-auto.px-4.sm:px-6.lg:px-0.py-8.sm:py-16
  .mx-auto.max-w-4xl.space-y-6
    div class="px-4 sm:px-6 lg:px-8"
      div class="sm:flex sm:items-center"
        div class="sm:flex-auto"
          h1 class="text-base font-semibold leading-6 text-gray-900" Statements
        div class="mt-4 sm:ml-16 sm:mt-0 sm:flex-none"
          = link_to "New Statement", new_statement_path, class: "button button__primary"

      div class="mt-8 flow-root"
        div class="-mx-4 -my-2 overflow-x-auto sm:-mx-6 lg:-mx-8"
          div class="inline-block min-w-full py-2 align-middle sm:px-6 lg:px-8"
            div class="overflow-hidden shadow ring-1 ring-black ring-opacity-5 sm:rounded-lg"
              table class="min-w-full divide-y divide-gray-300"
                thead class="bg-gray-50"
                  tr
                    th scope="col" class="py-3.5 pl-4 pr-3 text-left text-sm font-semibold text-gray-900 sm:pl-6" Date
                    th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900" Disposable Income
                    th scope="col" class="px-3 py-3.5 text-left text-sm font-semibold text-gray-900" Rating
                    th scope="col" class="relative py-3.5 pl-3 pr-4 sm:pr-6"
                tbody class="divide-y divide-gray-200 bg-white"
                  - @statements.each do |statement|
                    tr
                      td class="whitespace-nowrap py-4 pl-4 pr-3 text-sm font-medium text-gray-900 sm:pl-6" = l(statement.date, format: :long)
                      td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500" = statement.disposable_income
                      td class="whitespace-nowrap px-3 py-4 text-sm text-gray-500" = statement.rating
                      td class="relative whitespace-nowrap py-4 pl-3 pr-4 text-right text-sm font-medium sm:pr-6"
                        = link_to 'View', statement_path(statement), class: "text-indigo-600 hover:text-indigo-900"

app/views/statements/new.html.slim
.container.mx-auto.px-4.sm:px-6.lg:px-0.py-8.sm:py-16
  .mx-auto.max-w-3xl.space-y-6
    .card.py-8.px-6
      .flex.justify-between.items-center
        h1.font-semibold.text-xl.text-purple-900 New Statement
        = link_to "Back", statements_path, class: "button__underline"
      .py-5
        = render "form", statement: @statement

app/views/statements/show.html.slim
.container.mx-auto.px-4.sm:px-6.lg:px-0.py-8.sm:py-16
  .mx-auto.max-w-4xl.space-y-6
    .card.py-8.px-6
      .flex.justify-between.items-center
        h1.text-xl.font-semibold.leading-6.text-gray-900 = "Statement #{l(@statement.date, format: :long)}"
        = link_to 'Back', statements_path, class: "button__underline"
      .mt-16.space-y-16
        .space-y-8
          .flex.justify-between.items-center
            h2.text-base.font-semibold.leading-6.text-gray-900 Income
            = link_to new_statement_income_path(@statement), class: "button button__white" do
              = inline_svg_tag 'plus.svg', class: 'h-4 w-4'
          .space-y-2
            - @statement.incomes.each do |income|
              .flex.justify-between.items-center
                .text-sm = income.name
                .text-sm.text-gray-600 = income.amount
          .flex.justify-between.items-center.border-t.py-2
            .text-sm.font-semibold Total income
            .text-sm.text-gray-600 = @statement.total_income
        .space-y-8
          .flex.justify-between.items-center
            h2.text-base.font-semibold.leading-6.text-gray-900 Expenditure
            = link_to new_statement_expense_path(@statement), class: "button button__white" do
              = inline_svg_tag 'plus.svg', class: 'h-4 w-4'
          .space-y-2
            - @statement.expenses.each do |expense|
              .flex.justify-between.items-center
                .text-sm = expense.name
                .text-sm.text-gray-600 = expense.amount
          .flex.justify-between.items-center.border-t.py-2
            .text-sm.font-semibold Total expenditure
            .text-sm.text-gray-600 = @statement.total_expense
        .flex.justify-between.items-center
          h2.text-base.font-semibold.leading-6.text-gray-900 Disposable Income
          .text-gray-600 = @statement.disposable_income
        .flex.justify-between.items-center
          h2.text-base.font-semibold.leading-6.text-gray-900 Rating
          .text-gray-600 = @statement.rating